// client/src/views/Bots.vue
<template>
  <div id="bots-page">
    <div class="mb-8">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h1 class="text-3xl font-bold text-text-900 mb-2" data-testid="text-page-title">Trading Bots</h1>
          <p class="text-text-500" data-testid="text-page-description">Manage and monitor your automated trading strategies</p>
        </div>
        <button 
          class="btn-primary"
          @click="openCreateBotModal"
          data-testid="button-create-bot"
        >
          <i class="fas fa-plus mr-2"></i>
          Create Bot
        </button>
      </div>

      <!-- Filters -->
      <div class="flex items-center space-x-4 mb-6">
        <select 
          class="border border-gray-300 rounded-rugira px-3 py-2 text-sm bg-white focus:border-brand-red"
          v-model="filters.exchange"
          data-testid="select-filter-exchange"
        >
          <option value="">All Exchanges</option>
          <option value="binance">Binance</option>
          <option value="coinbase">Coinbase</option>
          <option value="kraken">Kraken</option>
        </select>
        <select 
          class="border border-gray-300 rounded-rugira px-3 py-2 text-sm bg-white focus:border-brand-red"
          v-model="filters.status"
          data-testid="select-filter-status"
        >
          <option value="">All Status</option>
          <option value="running">Running</option>
          <option value="stopped">Stopped</option>
          <option value="error">Error</option>
        </select>
        <select 
          class="border border-gray-300 rounded-rugira px-3 py-2 text-sm bg-white focus:border-brand-red"
          v-model="filters.strategy"
          data-testid="select-filter-strategy"
        >
          <option value="">All Strategies</option>
          <option value="arbitrage">Arbitrage</option>
          <option value="ma_crossover">MA Crossover</option>
        </select>
      </div>
    </div>

    <!-- Bots Table -->
    <div class="card-rounded overflow-hidden">
      <div v-if="botsStore.isLoading" class="p-12 text-center" data-testid="loading-bots">
        <i class="fas fa-spinner fa-spin text-2xl text-text-500 mb-2"></i>
        <p class="text-text-500">Loading bots...</p>
      </div>
      <div v-else-if="botsStore.error" class="p-12 text-center" data-testid="error-bots">
        <i class="fas fa-exclamation-triangle text-2xl text-brand-red mb-2"></i>
        <p class="text-brand-red">{{ botsStore.error }}</p>
        <button class="btn-secondary mt-4" @click="botsStore.fetchBots()">
          Try Again
        </button>
      </div>
      <div v-else-if="filteredBots.length === 0" class="p-12 text-center" data-testid="empty-bots">
        <i class="fas fa-robot text-2xl text-text-500 mb-2"></i>
        <p class="text-text-500">No bots found matching your criteria</p>
      </div>
      <div v-else class="overflow-x-auto">
        <table class="w-full">
          <thead class="bg-bg-1 border-b border-gray-200">
            <tr>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-name">Bot Name</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-exchange">Exchange</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-pair">Trading Pair</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-strategy">Strategy</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-status">Status</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-pnl">P/L (24h)</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-heartbeat">Last Heartbeat</th>
              <th class="text-left py-3 px-6 text-sm font-semibold text-text-700" data-testid="header-actions">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr 
              v-for="bot in filteredBots" 
              :key="bot.id"
              class="table-row border-b border-gray-100 last:border-b-0"
              :data-testid="`row-bot-${bot.id}`"
            >
              <td class="py-4 px-6">
                <div class="flex items-center space-x-3">
                  <div class="w-8 h-8 bg-brand-red bg-opacity-10 rounded-lg flex items-center justify-center">
                    <i class="fas fa-robot text-brand-red"></i>
                  </div>
                  <span class="font-medium text-text-900" data-testid="text-bot-name">{{ bot.name }}</span>
                </div>
              </td>
              <td class="py-4 px-6 text-text-700" data-testid="text-bot-exchange">{{ bot.exchange }}</td>
              <td class="py-4 px-6 text-text-700" data-testid="text-bot-pair">{{ bot.tradingPair }}</td>
              <td class="py-4 px-6 text-text-700" data-testid="text-bot-strategy">{{ formatStrategy(bot.strategy) }}</td>
              <td class="py-4 px-6">
                <span 
                  class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
                  :class="getStatusClass(bot.status)"
                  data-testid="text-bot-status"
                >
                  <StatusIndicator :status="bot.status" class="mr-1" />
                  {{ formatStatus(bot.status) }}
                </span>
              </td>
              <td class="py-4 px-6">
                <span 
                  class="font-semibold"
                  :class="bot.pnl24h >= 0 ? 'text-brand-green' : 'text-brand-red'"
                  data-testid="text-bot-pnl"
                >
                  {{ formatPnL(bot.pnl24h) }}
                </span>
              </td>
              <td class="py-4 px-6 text-text-500 text-sm" data-testid="text-bot-heartbeat">
                {{ formatHeartbeat(bot.lastHeartbeat) }}
              </td>
              <td class="py-4 px-6">
                <div class="flex items-center space-x-2">
                  <button 
                    v-if="bot.status === 'running'"
                    class="text-brand-red hover:bg-brand-red hover:text-white px-2 py-1 rounded text-sm transition-colors"
                    @click="handleStopBot(bot.id)"
                    data-testid="button-stop-bot"
                  >
                    <i class="fas fa-stop"></i>
                  </button>
                  <button 
                    v-else
                    class="text-brand-green hover:bg-brand-green hover:text-white px-2 py-1 rounded text-sm transition-colors"
                    @click="handleStartBot(bot.id)"
                    data-testid="button-start-bot"
                  >
                    <i class="fas fa-play"></i>
                  </button>
                  <button 
                    class="text-text-500 hover:bg-gray-100 px-2 py-1 rounded text-sm transition-colors"
                    @click="handleViewBot(bot.id)"
                    data-testid="button-view-bot"
                  >
                    <i class="fas fa-eye"></i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, computed, reactive } from 'vue'
import { useBotsStore } from '../stores'
import StatusIndicator from '../components/UI/StatusIndicator.vue'
import type { Bot } from '../types'

const botsStore = useBotsStore()

const filters = reactive({
  exchange: '',
  status: '',
  strategy: ''
})

const filteredBots = computed(() => {
  return botsStore.bots.filter(bot => {
    if (filters.exchange && bot.exchange !== filters.exchange) return false
    if (filters.status && bot.status !== filters.status) return false
    if (filters.strategy && bot.strategy !== filters.strategy) return false
    return true
  })
})

onMounted(() => {
  botsStore.fetchBots()
})

const openCreateBotModal = () => {
  window.dispatchEvent(new Event('openCreateBotModal'))
}

const handleStartBot = async (botId: string) => {
  if (!confirm('Are you sure you want to start this bot?')) return
  await botsStore.startBot(botId)
}

const handleStopBot = async (botId: string) => {
  if (!confirm('Are you sure you want to stop this bot?')) return
  await botsStore.stopBot(botId)
}

const handleViewBot = (botId: string) => {
  // Navigate to bot details view
  console.log('View bot:', botId)
}

const formatStrategy = (strategy: string) => {
  const strategies: Record<string, string> = {
    'arbitrage': 'Arbitrage',
    'ma_crossover': 'MA Crossover'
  }
  return strategies[strategy] || strategy
}

const formatStatus = (status: string) => {
  return status.charAt(0).toUpperCase() + status.slice(1)
}

const getStatusClass = (status: string) => {
  switch (status) {
    case 'running':
      return 'bg-brand-green text-white'
    case 'stopped':
      return 'bg-gray-200 text-text-700'
    case 'error':
      return 'bg-brand-red text-white'
    default:
      return 'bg-gray-200 text-text-700'
  }
}

const formatPnL = (pnl: number) => {
  if (pnl === 0) return '$0.00'
  const sign = pnl >= 0 ? '+' : ''
  return `${sign}$${Math.abs(pnl).toFixed(2)}`
}

const formatHeartbeat = (heartbeat: Date | null) => {
  if (!heartbeat) return '--'
  const now = new Date()
  const diffMs = now.getTime() - heartbeat.getTime()
  const diffSeconds = Math.floor(diffMs / 1000)
  
  if (diffSeconds < 60) return `${diffSeconds} seconds ago`
  if (diffSeconds < 3600) return `${Math.floor(diffSeconds / 60)} minutes ago`
  return `${Math.floor(diffSeconds / 3600)} hours ago`
}
</script>

// client/src/pages/Bots.tsx
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { SkipLink } from '@/components/ui/skip-link';
import { EmptyState } from '@/components/ui/empty-state';
import { EnhancedTable, type ColumnDef } from '@/components/ui/enhanced-table';
import { ConfirmationDialog } from '@/components/ui/confirmation-dialog';
import { 
  Bot, 
  Play, 
  Square, 
  Settings, 
  TrendingUp, 
  TrendingDown,
  AlertTriangle,
  MoreHorizontal,
  Plus
} from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface BotData {
  id: string;
  name: string;
  strategy: string;
  status: 'running' | 'stopped' | 'error';
  exchange: string;
  pair: string;
  pnl24h: number;
  totalPnl: number;
  uptime: string;
  lastTrade: string;
}

const mockBots: BotData[] = [
  {
    id: '1',
    name: 'Alpha Grid Bot',
    strategy: 'Grid Trading',
    status: 'running',
    exchange: 'Binance',
    pair: 'BTC/USDT',
    pnl24h: 247.83,
    totalPnl: 1247.83,
    uptime: '5d 12h',
    lastTrade: '2 minutes ago'
  },
  {
    id: '2', 
    name: 'Beta Arbitrage',
    strategy: 'Arbitrage',
    status: 'running',
    exchange: 'Coinbase',
    pair: 'ETH/USD',
    pnl24h: -45.20,
    totalPnl: 892.41,
    uptime: '3d 8h',
    lastTrade: '15 minutes ago'
  },
  {
    id: '3',
    name: 'Gamma Momentum',
    strategy: 'Momentum',
    status: 'error',
    exchange: 'Kraken',
    pair: 'SOL/EUR',
    pnl24h: 0,
    totalPnl: -125.67,
    uptime: '0m',
    lastTrade: '2 hours ago'
  },
  {
    id: '4',
    name: 'Delta Mean Reversion',
    strategy: 'Mean Reversion',
    status: 'stopped',
    exchange: 'Binance',
    pair: 'ADA/USDT',
    pnl24h: 0,
    totalPnl: 456.78,
    uptime: '0m',
    lastTrade: '1 day ago'
  }
];

export default function Bots() {
  const [selectedBots, setSelectedBots] = useState<BotData[]>([]);
  const [filters, setFilters] = useState<string[]>([]);

  const handleStartBot = (botId: string) => {
    console.log('Starting bot:', botId);
  };

  const handleStopBot = (botId: string) => {
    console.log('Stopping bot:', botId);
  };

  const handleDeleteBot = (botId: string) => {
    console.log('Deleting bot:', botId);
  };

  const handleBulkStart = () => {
    console.log('Starting bots:', selectedBots.map(b => b.id));
  };

  const handleBulkStop = () => {
    console.log('Stopping bots:', selectedBots.map(b => b.id));
  };

  const getStatusBadge = (status: BotData['status']) => {
    const variants = {
      running: 'bg-green-100 text-green-800',
      stopped: 'bg-gray-100 text-gray-800', 
      error: 'bg-red-100 text-red-800'
    };
    
    return (
      <Badge className={variants[status]}>
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </Badge>
    );
  };

  const columns: ColumnDef<BotData>[] = [
    {
      id: 'name',
      header: 'Bot Name',
      accessorKey: 'name',
      sortable: true,
      cell: (bot) => (
        <div className="flex items-center space-x-3">
          <Bot className="h-5 w-5 text-gray-400" />
          <div>
            <div className="font-medium text-gray-900">{bot.name}</div>
            <div className="text-sm text-gray-500">{bot.strategy}</div>
          </div>
        </div>
      )
    },
    {
      id: 'status',
      header: 'Status',
      accessorKey: 'status',
      sortable: true,
      filterable: true,
      cell: (bot) => getStatusBadge(bot.status)
    },
    {
      id: 'exchange',
      header: 'Exchange',
      accessorKey: 'exchange',
      sortable: true,
      filterable: true,
      cell: (bot) => (
        <div>
          <div className="font-medium">{bot.exchange}</div>
          <div className="text-sm text-gray-500">{bot.pair}</div>
        </div>
      )
    },
    {
      id: 'pnl24h',
      header: '24h P&L',
      accessorKey: 'pnl24h',
      sortable: true,
      cell: (bot) => (
        <div className={`flex items-center space-x-1 ${
          bot.pnl24h > 0 ? 'text-green-600' : bot.pnl24h < 0 ? 'text-red-600' : 'text-gray-600'
        }`}>
          {bot.pnl24h > 0 ? <TrendingUp className="h-4 w-4" /> : 
           bot.pnl24h < 0 ? <TrendingDown className="h-4 w-4" /> : null}
          <span>${bot.pnl24h.toFixed(2)}</span>
        </div>
      )
    },
    {
      id: 'totalPnl',
      header: 'Total P&L',
      accessorKey: 'totalPnl',
      sortable: true,
      cell: (bot) => (
        <span className={`font-medium ${
          bot.totalPnl > 0 ? 'text-green-600' : bot.totalPnl < 0 ? 'text-red-600' : 'text-gray-600'
        }`}>
          ${bot.totalPnl.toFixed(2)}
        </span>
      )
    },
    {
      id: 'uptime',
      header: 'Uptime',
      accessorKey: 'uptime',
      sortable: true
    },
    {
      id: 'actions',
      header: 'Actions',
      cell: (bot) => (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="sm" data-testid={`bot-actions-${bot.id}`}>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem 
              onClick={() => handleStartBot(bot.id)}
              disabled={bot.status === 'running'}
            >
              <Play className="h-4 w-4 mr-2" />
              Start
            </DropdownMenuItem>
            <DropdownMenuItem 
              onClick={() => handleStopBot(bot.id)}
              disabled={bot.status === 'stopped'}
            >
              <Square className="h-4 w-4 mr-2" />
              Stop
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Settings className="h-4 w-4 mr-2" />
              Configure
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem 
              onClick={() => handleDeleteBot(bot.id)}
              className="text-red-600"
            >
              <AlertTriangle className="h-4 w-4 mr-2" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )
    }
  ];

  const tableFilters = [
    { id: 'running', label: 'Running', value: 'running' },
    { id: 'stopped', label: 'Stopped', value: 'stopped' },
    { id: 'error', label: 'Error', value: 'error' },
    { id: 'binance', label: 'Binance', value: 'binance' },
    { id: 'coinbase', label: 'Coinbase', value: 'coinbase' }
  ];

  const bulkActions = (
    <div className="flex space-x-2">
      <Button size="sm" onClick={handleBulkStart} data-testid="bulk-start">
        <Play className="h-4 w-4 mr-1" />
        Start
      </Button>
      <ConfirmationDialog
        trigger={
          <Button size="sm" variant="outline" data-testid="bulk-stop">
            <Square className="h-4 w-4 mr-1" />
            Stop
          </Button>
        }
        title="Stop Selected Bots"
        description="Are you sure you want to stop the selected trading bots? This will halt their operations and close any pending orders."
        confirmText="Stop Bots"
        onConfirm={handleBulkStop}
        variant="destructive"
      />
    </div>
  );

  return (
    <div className="space-y-6 p-6">
      <SkipLink href="#bots-table">Skip to bots table</SkipLink>
      
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Trading Bots</h1>
          <p className="text-gray-600">Manage and monitor your automated trading strategies</p>
        </div>
        <Button data-testid="create-bot">
          <Plus className="h-4 w-4 mr-2" />
          Create Bot
        </Button>
      </div>

      <div id="bots-table">
        {mockBots.length === 0 ? (
          <EmptyState
            icon={<Bot className="h-12 w-12" />}
            title="No trading bots found"
            description="Get started by creating your first automated trading bot to begin generating profits."
            action={{
              label: "Create Your First Bot",
              onClick: () => console.log('Create bot')
            }}
          />
        ) : (
          <EnhancedTable
            data={mockBots}
            columns={columns}
            searchPlaceholder="Search bots by name, strategy, or exchange..."
            filters={tableFilters}
            selectedFilters={filters}
            onFilterChange={setFilters}
            onSelectionChange={setSelectedBots}
            bulkActions={bulkActions}
            pageSize={10}
          />
        )}
      </div>
    </div>
  );
}
