// client/src/components/UI/StatusIndicator.vue
<template>
  <span 
    class="status-indicator"
    :class="statusClass"
    data-testid="status-indicator"
  ></span>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  status: 'online' | 'warning' | 'error' | 'offline' | 'connected' | 'disconnected'
}

const props = defineProps<Props>()

const statusClass = computed(() => {
  switch (props.status) {
    case 'online':
    case 'connected':
      return 'status-online'
    case 'warning':
      return 'status-warning'
    case 'error':
    case 'offline':
    case 'disconnected':
      return 'status-error'
    default:
      return 'status-error'
  }
})
</script>

// client/src/components/UI/StatusIndicator.tsx
import React from "react";

interface StatusIndicatorProps {
  status: 'online' | 'warning' | 'error' | 'offline' | 'connected' | 'disconnected';
  className?: string;
}

export default function StatusIndicator({ status, className = "" }: StatusIndicatorProps) {
  
  const getStatusClass = () => {
    switch (status) {
      case 'online':
      case 'connected':
        return 'status-online';
      case 'warning':
        return 'status-warning';
      case 'error':
      case 'offline':
      case 'disconnected':
        return 'status-error';
      default:
        return 'status-error';
    }
  };

  return (
    <span 
      className={`status-indicator ${getStatusClass()} ${className}`}
      data-testid="status-indicator"
    ></span>
  );
}
